version: '2'
services:
    configuration-app:
        image: configuration
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://configuration-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=configuration
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    configuration-mongodb:
        extends:
            file: mongodb.yml
            service: configuration-mongodb
